package com.danneu.kog


object Mime {
    val extensions = mapOf(
        "7z" to "application/x-7z-compressed",
        "aac" to "audio/aac",
        "ai" to "application/postscript",
        "appcache" to "text/cache-manifest",
        "asc" to "text/plain",
        "atom" to "application/atom+xml",
        "avi" to "video/x-msvideo",
        "bin" to "application/octet-stream",
        "bmp" to "image/bmp",
        "bz2" to "application/x-bzip",
        "class" to "application/octet-stream",
        "cer" to "application/pkix-cert",
        "crl" to "application/pkix-crl",
        "crt" to "application/x-x509-ca-cert",
        "css" to "text/css",
        "csv" to "text/csv",
        "deb" to "application/x-deb",
        "dart" to "application/dart",
        "dll" to "application/octet-stream",
        "dmg" to "application/octet-stream",
        "dms" to "application/octet-stream",
        "doc" to "application/msword",
        "dvi" to "application/x-dvi",
        "edn" to "application/edn",
        "eot" to "application/vnd.ms-fontobject",
        "eps" to "application/postscript",
        "etx" to "text/x-setext",
        "exe" to "application/octet-stream",
        "flv" to "video/x-flv",
        "flac" to "audio/flac",
        "gif" to "image/gif",
        "gz" to "application/gzip",
        "htm" to "text/html",
        "html" to "text/html",
        "ico" to "image/x-icon",
        "iso" to "application/x-iso9660-image",
        "jar" to "application/java-archive",
        "jpe" to "image/jpeg",
        "jpeg" to "image/jpeg",
        "jpg" to "image/jpeg",
        "js" to "text/javascript",
        "com/danneu/kog/jsondanneu/kog/json" to "application/json",
        "lha" to "application/octet-stream",
        "lzh" to "application/octet-stream",
        "mov" to "video/quicktime",
        "m4v" to "video/mp4",
        "mp3" to "audio/mpeg",
        "mp4" to "video/mp4",
        "mpe" to "video/mpeg",
        "mpeg" to "video/mpeg",
        "mpg" to "video/mpeg",
        "oga" to "audio/ogg",
        "ogg" to "audio/ogg",
        "ogv" to "video/ogg",
        "pbm" to "image/x-portable-bitmap",
        "pdf" to "application/pdf",
        "pgm" to "image/x-portable-graymap",
        "png" to "image/png",
        "pnm" to "image/x-portable-anymap",
        "ppm" to "image/x-portable-pixmap",
        "ppt" to "application/vnd.ms-powerpoint",
        "ps" to "application/postscript",
        "qt" to "video/quicktime",
        "rar" to "application/x-rar-compressed",
        "ras" to "image/x-cmu-raster",
        "rb" to "text/plain",
        "rd" to "text/plain",
        "rss" to "application/rss+xml",
        "rtf" to "application/rtf",
        "sgm" to "text/sgml",
        "sgml" to "text/sgml",
        "svg" to "image/svg+xml",
        "swf" to "application/x-shockwave-flash",
        "tar" to "application/x-tar",
        "tif" to "image/tiff",
        "tiff" to "image/tiff",
        "ttf" to "application/x-font-ttf",
        "txt" to "text/plain",
        "webm" to "video/webm",
        "wmv" to "video/x-ms-wmv",
        "woff" to "application/font-woff",
        "xbm" to "image/x-xbitmap",
        "xls" to "application/vnd.ms-excel",
        "xml" to "text/xml",
        "xpm" to "image/x-xpixmap",
        "xwd" to "image/x-xwindowdump",
        "zip" to "application/zip"
    )

    fun fromExtension(extension: String): String {
        return extensions.getOrDefault(extension, "application/octet-stream")
    }
}
